#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "FILE_STRUCTURE_GRAPH.md"
IGNORE_DIRS = {
    ".git",
    ".gradle",
    ".idea",
    ".next",
    ".nuxt",
    ".svelte-kit",
    ".vscode",
    "build",
    "coverage",
    "dist",
    "node_modules",
}


def should_skip(path: Path) -> bool:
    return any(part in IGNORE_DIRS for part in path.relative_to(ROOT).parts)


def render_tree(path: Path, prefix: str = "") -> list[str]:
    entries = [
        child
        for child in sorted(path.iterdir(), key=lambda p: (not p.is_dir(), p.name.lower()))
        if not should_skip(child) and child.name != OUTPUT.name
    ]
    lines: list[str] = []
    for index, child in enumerate(entries):
        connector = "`-- " if index == len(entries) - 1 else "|-- "
        suffix = "/" if child.is_dir() else ""
        lines.append(f"{prefix}{connector}{child.name}{suffix}")
        if child.is_dir():
            extension = "    " if index == len(entries) - 1 else "|   "
            lines.extend(render_tree(child, prefix + extension))
    return lines


def main() -> None:
    lines = [
        "# File Structure Graph",
        "",
        "Generated by `scripts/update_file_structure_graph.py`.",
        "",
        "```text",
        f"{ROOT.name}/",
        *render_tree(ROOT),
        "```",
        "",
    ]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()

